main_loop_for_robot:
  poetry run robot-main-loop

debug_loop_for_robot:
  poetry run robot-main-loop-debug

mock_fifo_run:
  poetry run fifo-test

mock_serial_run:
  poetry run serial-test

check_typing:
  poetry run mypy .
