main_loop_for_robot:
  poetry run robot-main-loop --config ./robot_settings/main.toml

debug_loop_for_robot:
  poetry run test-main-loop --config ./robot_settings/debug.toml

debug_socket_loop_for_robot:
  poetry run test-main-loop --config ./robot_settings/socket_debug.toml

mock_socket_run:
  poetry run socket-mock-esp --config ./robot_settings/socket_debug.toml

mock_serial_run:
  poetry run serial-mock-esp --config ./robot_settings/debug_mock.toml

start_virtual_serial_bridge:
  socat -d -d pty,raw,echo=0 pty,raw,echo=0

check_typing:
  poetry run mypy .
