# Makefile for using cli in neovim instead of Platformio IDE
# Uncomment lines below if you have problems with $PATH
#SHELL := /bin/bash
#PATH := /usr/local/bin:$(PATH)

initlsp:
	pio -f -c vim run -t compiledb
